### PR TITLE
 #41 Use Classpath provided by Maven Core for AJC command

### PR DESCRIPTION
**Pull request by mgreau**
- Configure the ajc Mojo with "requiresDependencyResolution = ResolutionScope.COMPILE"
  - Add classpathElements field as @Parameter with ${project.compileClasspathElements} default value
  - Remove all unnecessary code previously used to generate classpath

### CODE REVIEW

**Comment by caarlos0** [comment]
Nice!

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by mgreau** [comment]
Thanks :)
Do you plan to do a release with this fix?

**Comment by caarlos0** [comment]
@mgreau i think it will be released soon, yeah

**Comment by mgreau** [comment]
Cool!

**Pull request merged**
