### PR TITLE
#22 log4j configuration

### PR DESCRIPTION
**Pull request by maurezen**
Added a basic log4j configuration.

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, let me find someone who can review this pull request

**Comment by dmarkov** [comment]
@yegor256 please review

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 Thanks a lot, I just topped your account for **16 mins**, transaction ID `000-5891d91b`... +16 added to your rating, current score is: [+4730](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
