### PR TITLE
#21 a test was enabled

### PR DESCRIPTION
**Pull request by darkled**

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks, let me find someone who can review this pull request

**Comment by dmarkov** [comment]
@yegor256 please review

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by dmarkov** [comment]
@yegor256 Many thanks! **16 mins** were added to your account in Transaction ID `000-1fee9f62`... added +16 to your rating, now it is equal to [+4714](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
