### PR TITLE
#25 Copyright section is outdated 

### PR DESCRIPTION
**Pull request by palyuga**
PR with a fixed issue #25

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks for the pull request, let me find a reviewer..

**Comment by dmarkov** [comment]
@yegor256 this pull request is for you, please review

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by dmarkov** [comment]
@yegor256 thank you, added **16 mins** to your acc, payment num is `000-907eb40a`... added +16 to your rating, now it is equal to [+4854](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
