### PR TITLE
Add Javadoc badge with automatic version detection

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by dmarkov** [comment]
@valery1707 Thanks for your pull request, let me find someone who can review it

**Comment by dmarkov** [comment]
@yegor256 review this pull request please, it is rather short for a full review

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 done, I added **16 mins** in payment `000-797c6ef8`, 69 hours and 42 mins spent to complete this... review comments (c=1) added as a bonus... +16 added to your rating, at the moment it is: [+4432](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
