### PR TITLE
Issue #1.

### PR DESCRIPTION
**Pull request by dpisarenko**
Issue: https://github.com/jcabi/jcabi-maven-plugin/issues/1

### CODE REVIEW

**Comment by dmarkov** [comment]
Thanks for the pull request, let me find a reviewer..

**Comment by dpisarenko** [comment]
@dmarkov Please find someone to review this PR. Thanks.

**Comment by dmarkov** [comment]
@carlosmiranda review this one please

**Comment by carlosmiranda** [comment]
@rultor Merge please.

**Comment by dpisarenko** [comment]
@carlosmiranda Rultor didn't respond after more than half an hour, which is unusual. Could you please look, what happened?

**Comment by carlosmiranda** [comment]
@rultor Try to merge please.

**Comment by dmarkov** [comment]
@carlosmiranda I just added **17 mins** to your account, many thanks for your contribution..... +17 to your rating, your total score is [+1851](http://www.netbout.com/b/35023?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
