### PR TITLE
Upgrade to aspectjtools v1.8.6

### PR DESCRIPTION
**Pull request by cvrebert**

### CODE REVIEW

**Comment by dmarkov** [comment]
@cvrebert Many thanks, I will find someone to review it before we merge

**Comment by dmarkov** [comment]
@yegor256 review this pls (it's a rather short pull request)

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor release, tag is `0.13`

**Comment by dmarkov** [comment]
@yegor256 done, I added **17 mins** in payment `000-2fca1367`, 23 hours and 52 mins spent to complete this... you're getting extra minutes here (c=2)... +17 to your rating, your total score is [+5889](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
