### PR TITLE
Missing documentation about JSR-303 #13

### PR DESCRIPTION
**Pull request by nhekfqn**

### CODE REVIEW

**Comment by dmarkov** [comment]
Many thanks for the PR, let me find a reviewer for it

**Comment by dmarkov** [comment]
@krzyk review this one please

**Comment by krzyk** [comment]
@nhekfqn Please add information when it is required (see https://github.com/teamed/qulice/pull/363)

**Comment by nhekfqn** [comment]
@krzyk do you mean JDK version?

**Comment by krzyk** [comment]
@nhekfqn no, I mean that when one sees JSR-303 error in the build then he/she should add such dependency

**Comment by nhekfqn** [comment]
@krzyk added a note about jsr-303. Please review.

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by dmarkov** [comment]
@krzyk thanks, I just added **15 mins** to your account, payment `50954197`

+15 to your rating, your total score is [+3252](http://www.netbout.com/b/35035?open=rating)

**Comment by dmarkov** [comment]
@rultor please deploy

**Pull request merged**
