### PR TITLE
Default temp directory should be cleaned after every execution to avoid unexpected behavior

### PR DESCRIPTION
**Pull request by piddubnyi**
Solving https://github.com/jcabi/jcabi-maven-plugin/issues/40
Added cleanup of temp directory.

### CODE REVIEW

**Comment by dmarkov** [comment]
@piddubnyi Thanks, I will find someone to review this PR soon

**Comment by dmarkov** [comment]
@yegor256 review it please, it is a rather short pull request, no need to do a full code review

**Comment by piddubnyi** [comment]
@yegor256 I can't see the reason of build fail, is it ok to leave it as is ?

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by piddubnyi** [comment]
@yegor256 I fixed build by removing assertion in groovy script. Please check if it is acceptable.

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@yegor256 **17 mins** was added to your account, many thanks for your contribution (payment 000-dfc53478)! The task took 120 hours and 30 mins.

you're getting extra minutes here (c=2)

+17 added to your rating, current score is: [+4482](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
